[package]
authors = ["kngwyu <yuji.kngw.80s.revive@gmail.com>"]
edition = "2018"
name = "fsl"
version = "0.1.0"

[dependencies]
structopt = "0.3"
anyhow = "1.0.26"
euclid = "0.20.7"
crossterm = "0.16.0"
